-- MySQL Script generated by MySQL Workbench
-- Tue Nov 21 16:37:02 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bead1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bead1` DEFAULT CHARACTER SET utf8 ;
USE `bead1` ;

-- -----------------------------------------------------
-- Table `bead1`.`user_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bead1`.`user_table` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `passwd` VARCHAR(255) NULL DEFAULT NULL,
  `unique_alias` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bead1`.`pencil_case`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bead1`.`pencil_case` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `owner` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK705xjcoqq5wq7icino216l4ks` (`owner` ASC),
  CONSTRAINT `FK705xjcoqq5wq7icino216l4ks`
    FOREIGN KEY (`owner`)
    REFERENCES `bead1`.`user_table` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bead1`.`pencil_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bead1`.`pencil_table` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `brand` VARCHAR(255) NULL DEFAULT NULL,
  `color` VARCHAR(255) NULL DEFAULT NULL,
  `length_column` INT(11) NULL DEFAULT NULL,
  `sharpness` INT(11) NULL DEFAULT NULL,
  `pencil_case` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKmwaig6vjvxdj8348y5wxk5moc` (`pencil_case` ASC),
  CONSTRAINT `FKmwaig6vjvxdj8348y5wxk5moc`
    FOREIGN KEY (`pencil_case`)
    REFERENCES `bead1`.`pencil_case` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
